kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydep
spec:
  replicas: 3 
  selector:
    matchLabels:
      luv: jos
  template:
    metadata:
      name: joston
      labels:
        luv: jos
    spec:
      containers:
          - name: con1
            image: luvisjostonj/3-tier:v1
